services:
  db:
    image: postgres:16
    container_name: tn-pg
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: website_builder
    ports:
      - "5432:5432"
    volumes:
      - tn-pg-data:/var/lib/postgresql/data

volumes:
  tn-pg-data:
